Repository gbowne1/gbowne1site_react, pull requests merged in 2023-10, with the labels that each got.

#41 Fix a11y issues
  src/assets/styles/Blog.css
  src/assets/styles/Contact.css
  src/assets/styles/Footer.css
  src/assets/styles/Header.css
  src/assets/styles/NavBar.css
  src/components/About.jsx
  src/components/Blog.jsx
  src/components/Contact.jsx
  src/components/CookieBar.jsx
  src/components/Footer.jsx
  src/components/Gallery.jsx
  src/components/NavBar.jsx
Labels: bug, enhancement, help wanted, good first issue

#43 Fix/top nabar issues
  src/App.css
  src/App.js
  src/assets/styles/NavBar.css
  src/components/NavBar.jsx
Labels: bug, enhancement, help wanted

#46 Fix: Adjusted height to 200vh for proper display of the footer
  src/assets/styles/Contact.css
  src/assets/styles/Footer.css
  src/components/Contact.jsx
  src/components/Header.jsx
Labels: bug, help wanted, good first issue

#47 Fix/footer issues
  src/assets/styles/Footer.css
  src/components/Footer.jsx
Labels: enhancement, help wanted
